---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-3241
    - profile-3241
    - user-3241
    - webserver-3241

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"
